.github/PULL_REQUEST_TEMPLATE.md
=> Feature #1 Update pull request template

.gitignore
🔒 Close #3
- .gitignore
- New gitignore
=> [Project] #3 : Add gitignore

.gitattributes
🔒 Close #5 
- .gitattributes
- [git-scm](https://git-scm.com/book/ko/v2/Git맞춤-Git-Attributes)
=> [Project] #5 : Add Gitattributes

campair/campair.xcodeproj/project.pbxproj, campair/campair/View/ToolDictionary/ToolDictionaryMainView.swift
🔒 Close #16 
🔒 Close #17 
- campair/campair.xcodeproj/project.pbxproj
- campair/campair/View/ToolDictionary/ToolDictionaryMainView.swift
- Create the ToolDictionaryMainView's SearchBar UI 
- Create the ToolDictionaryMainView's GridView UI
=> [Feature] #16, #17 : Add ToolDictionaryMainView UI

campair/campair.xcodeproj/project.pbxproj
🔒 Close #24
- campair/campair.xcodeproj/project.pbxproj
=> [Bug] #24 : resolved error

campair/campair.xcodeproj/project.pbxproj, campair/campair/View/ToolDictionary/ToolDictionaryDetailView.swift
🔒 Close #19 
🔒 Close #20 
- campair/campair/View/ToolDictionaryDetailView.swift
- Create the ToolDictionaryDetailView's SearchBar UI (ScrollView , show detail tools)
- I don't know if I split the view in a good way.
=> [Feature] #19, #20 : Add ToolDictionaryDetailView UI

campair/campair/View/Editor/EditorDetailView.swift, campair/campair/View/EquipmentDictionary/EquipmentDictionaryDetailView.swift, campair/campair/View/EquipmentDictionary/EquipmentDictionaryMainView.swift, campair/campair/ViewModel/EditorViewModel.swift
🔒 Close #33
- campair/campair/View/Editor/EditorDetailView.swift
- campair/campair/ViewModel/EditorViewModel.swift
- make EditorDetailViewModel
- binding EditorDetailView Data
- EditorDetailViewModel class structure
- EditorDetailViewModel data binding
- @sustainable-git 
I think we should change swiftLint that "Line should be 200 characters or less". Because I am experiencing inconvenience when working with fake data.
=> [Feature] #33 EditorDetailView Data Binding

campair/campair/Entity/Editor/Main/EditorMainContent.swift, campair/campair/Entity/EditorMainCollectionData.json, campair/campair/View/ContentView.swift
🔒 Close #57
- campair/campair/Entity/Editor/Main/EditorMainContent.swift
- campair/campair/Entity/EditorMainCollectionData.json
- campair/campair/View/ContentView.swift
- add ContentID in EditorMainContent
=> [Refactor] #57 Revise Editor Entity

campair/campair.xcodeproj/project.pbxproj, campair/campair/Entity/Dictionary/Content/temp3.swift, campair/campair/Entity/Dictionary/Detail/temp2.swift, campair/campair/Entity/Dictionary/Main/temp1.swift
🔒 Close #69
- 
- adding contents to empty folders
=> [Refactor] #69 adding contents to empty folders

campair/campair/Entity/Editor/ContentEquipment.swift, campair/campair/Entity/Editor/Main/EditorMainCollection.swift, campair/campair/Entity/Editor/Main/EditorMainContent.swift
🔒 Close #76 
campair/campair/Entity/Editor/ContentEquipment.swift
campair/campair/Entity/Editor/Main/EditorMainCollection.swift
campair/campair/Entity/Editor/Main/EditorMainContent.swift
- Refactor initializer as paramater init.
=> [Refactor] #76 Refactor Editor's initializer

campair/campair/Entity/Editor/Detail/EditorDetailContent.swift, campair/campair/Entity/Editor/Detail/EquipmentContent.swift, campair/campair/Entity/Editor/Detail/OpeningSection.swift, campair/campair/Json/Editor/EditorDetailContentData.json, campair/campair/Model/EditorRepository.swift, campair/campair/UseCase/EditorUseCase.swift, campair/campair/View/ContentView.swift, campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailContentsVersionView.swift, campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailListVersionView.swift, campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailView.swift, campair/campair/View/Editor/Detail/EditorRecommendEquipmentView.swift, campair/campair/View/Editor/Detail/OpeningEditorView.swift, campair/campair/View/Editor/Detail/RecommendedEquipmentCardView.swift, campair/campair/ViewModel/Editor/EditorDetailViewModel.swift
🔒 Close #73
🔒 Close #78
Entity (
campair/campair/Entity/Editor/Detail/EditorDetailContent.swift
campair/campair/Entity/Editor/Detail/EquipmentContent.swift
campair/campair/Entity/Editor/Detail/OpeningSection.swift
)
View (
campair/campair/View/ContentView.swift
campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailListVersionView.swift
campair/campair/View/Editor/Detail/EditorRecommendEquipmentView.swift
campair/campair/View/Editor/Detail/OpeningEditorView.swift
campair/campair/View/Editor/Detail/RecommendedEquipmentCardView.swift
)
campair/campair/Json/Editor/EditorDetailContentData.json …
=> [Feature] #73 #78 Editor DetailView DataBinding

campair/campair/Utility/ViewExtension.swift, campair/campair/View/Dictionary/Content/DictionaryContentView.swift, campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailContentsVersionView.swift
🔒 Close #23
campair/campair/Utility/ViewExtension.swift
campair/campair/View/Dictionary/Content/DictionaryContentView.swift
- add DictionaryEquipmentContentView's hifi UI
=> [Feature] #23 DictionaryEquipmentContentView's hifi UI

campair/campair.xcodeproj/project.pbxproj
🔒 Close #86 
Delete Equipment's "폴대" Image
- We need take care of overlap image name, it yield error.
- https://zetal.tistory.com/entry/Multiple-commands-produce-Error-해결법
=> [Bug] #86 HOTFIX! Multiple commands produce Error

campair/campair/Application/CampairApp.swift, campair/campair/Entity/Dictionary/Main/DictionaryMainCategory.swift, campair/campair/Json/Editor/Detail/DictionaryMainCollectionData.json, campair/campair/Model/DictionaryRepository.swift, campair/campair/ViewModel/Dictionary/DictionaryMainViewModel.swift
🔒 Close #95
campair/campair/Application/CampairApp.swift
campair/campair/Entity/Dictionary/Main/DictionaryMainCategory.swift
campair/campair/Json/Editor/Detail/DictionaryMainCollectionData.json
campair/campair/Model/DictionaryRepository.swift
campair/campair/ViewModel/Dictionary/DictionaryMainViewModel.swift
- DictionaryMainView Entity property name changed
=> [Refactor] #95 DictionaryMainView Entity property name changed 

campair/campair/Application/CampairApp.swift, campair/campair/Entity/Dictionary/Content/DictionaryEquipmentContent.swift, campair/campair/Entity/Dictionary/Detail/DictionaryDetailCategory.swift, campair/campair/Entity/Dictionary/Detail/EquipmentList.swift, campair/campair/Entity/Dictionary/Main/DictionaryMainCategory.swift, campair/campair/Entity/Dictionary/Main/DictionaryMainCollection.swift, campair/campair/Entity/Editor/Detail/OpeningSection.swift, campair/campair/Json/Editor/Detail/Content_2.json, campair/campair/Json/Editor/Detail/DictionaryMainCollectionData.json, campair/campair/View/Dictionary/Content/DictionaryContentView.swift, campair/campair/View/Dictionary/Main/DictionaryMainView.swift, campair/campair/View/Editor/Main/EditorMainView.swift
🔒 Close #100
🔒 Close #(issue-number2)
campair/campair/Application/CampairApp.swift
campair/campair/Entity/Dictionary/Content/DictionaryEquipmentContent.swift
campair/campair/Entity/Dictionary/Detail/DictionaryDetailCategory.swift
campair/campair/Entity/Dictionary/Detail/EquipmentList.swift
campair/campair/Entity/Dictionary/Main/DictionaryMainCategory.swift
campair/campair/Entity/Dictionary/Main/DictionaryMainCollection.swift
campair/campair/Entity/Editor/Detail/OpeningSection.swift
campair/campair/Json/Editor/Detail/Content_2.json
campair/campair/Json/Editor/Detail/DictionaryMainCollectionData.json
campair/campair/View/Dictionary/Content/DictionaryContentView.swift
campair/campair/View/Dictionary/Main/DictionaryMainView.swift …
=> [Refactor] #100 fix DetailMainView UI to use json

campair/campair.xcodeproj/project.pbxproj, campair/campair/Application/CampairApp.swift, campair/campair/Json/Dictionary/경량_의자.json, campair/campair/Model/EditorRepository.swift, campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailView.swift, campair/campair/View/Editor/Main/EditorCardView.swift, campair/campair/View/Editor/Main/EditorMainView.swift
🔒 Close #92 
campair/campair.xcodeproj/project.pbxproj
campair/campair/Entity/Dictionary/Content/DictionaryEquipmentContent.swift
"campair/campair/Json/Dictionary/\352\262\275\353\237\211_\354\235\230\354\236\220.json"
campair/campair/View/Dictionary/Content/DictionaryContentView.swift
- Can transition EditorMainView -> EditorDetailView
-
=> [Feature]  #92 EditorMainView -> EditorDetailView transition

campair/campair/Application/CampairApp.swift, campair/campair/Json/Editor/Detail/Content_2.json, campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailContentsVersionView.swift, campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailListVersionView.swift, campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailView.swift
🔒 Close #104
campair/campair/Application/CampairApp.swift
campair/campair/Json/Editor/Detail/Content_2.json
campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailListVersionView.swift
- An error occurred while changing the entity, so I solved the code that I commented on.
=> [Bug] #104 fix EditorDetailListVersionView errors

campair/campair.xcodeproj/project.pbxproj, campair/campair/Json/Dictionary/Equipment/경량_의자.json, campair/campair/Json/Dictionary/경량_의자.json, campair/campair/Model/DictionaryRepository.swift, campair/campair/UseCase/DictionaryUseCase.swift, campair/campair/View/ContentView.swift, campair/campair/View/Dictionary/Content/DictionaryContentView.swift, campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailView.swift, campair/campair/ViewModel/Dictionary/DictionaryContentViewModel.swift
🔒 Close #106 
- Do Data binding
=> [Feature] #106 DictionaryContentViewDataBinding

campair/campair/Application/Assets.xcassets/moreEquipmentPainting.imageset/Contents.json, campair/campair/View/Dictionary/Detail/DictionaryDetailedView.swift, campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailContentsVersionView.swift, campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailListVersionView.swift, campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailView.swift, campair/campair/View/Editor/Detail/ShareRecommendedEquipmentView.swift, campair/campair/ViewModel/Dictionary/DictionaryDetailViewModel.swift
🔒 Close #108 
campair/campair/View/Dictionary/Detail/DictionaryDetailedView.swift
campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailListVersionView.swift
campair/campair/View/Editor/Detail/ShareRecommendedEquipmentView.swift
- Can navigate to DictionaryDetailView from EditorDetailView
=> [Feature] #108 Navigation more see equipments at EditorDetailView

campair/campair/View/Editor/Main/EditorMainView.swift
🔒 Close #112 
- Navigation EditorMainView to DictionaryContentView
=> [Feature] #112 Navigation EditorMainView to DictionaryContentView

campair/campair/View/TabbarView.swift
🔒 Close #114 
- campair/campair/View/TabbarView.swift
- user can know where they are to see toolbarColor
=> [Feature] #114 add toolbar color

campair/campair/View/Dictionary/Content/DictionaryContentView.swift, campair/campair/View/Dictionary/Detail/DictionaryDetailedView.swift, campair/campair/View/Editor/Detail/RecommendedEquipmentCardView.swift, campair/campair/View/Editor/Main/EditorMainView.swift
🔒 Close #84
campair/campair/View/Dictionary/Content/DictionaryContentView.swift
campair/campair/View/Dictionary/Detail/DictionaryDetailedView.swift
campair/campair/View/Editor/Detail/RecommendedEquipmentCardView.swift
- Touch the detailed tool in ToolDictionaryDetailView to switch the tool dictionary content screen
=> [Feature] #84 DictionaryEquipmentContentView Data Binding

campair/campair.xcodeproj/project.pbxproj, campair/campair/Utility/DateExtension.swift, campair/campair/View/Editor/Main/EditorMainView.swift
🔒 Close #40 
campair/campair.xcodeproj/project.pbxproj
campair/campair/Utility/DateExtension.swift
- Can get todayPhase and changing EditorMainView's phase
=> [Feature] Depending on Date, change the phase in EditorMainView #40

campair/campair/View/Dictionary/Detail/DictionaryDetailedView.swift, campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailContentsVersionView.swift, campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailListVersionView.swift, campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailView.swift, campair/campair/View/Editor/Main/EditorCardView.swift
🔒 Close #121
campair/campair/View/Editor/Main/EditorCardView.swift
campair/campair/View/Dictionary/Detail/DictionaryDetailedView.swift
campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailListVersionView.swift
- x mark's color is changed while the background color changing
=> [Feature] #121 EditorDetailView's Color change 

campair/campair/Entity/Dictionary/Detail/DictionaryDetailCategory.swift, campair/campair/Model/DictionaryRepository.swift, campair/campair/UseCase/DictionaryDetailCategoryData.json, campair/campair/UseCase/DictionaryUseCase.swift, campair/campair/View/Dictionary/Content/DictionaryContentView.swift, campair/campair/View/Dictionary/Detail/DictionaryDetailedView.swift, campair/campair/View/Editor/Detail/RecommendedEquipmentCardView.swift, campair/campair/View/Editor/Main/EditorMainView.swift, campair/campair/ViewModel/Dictionary/DictionaryDetailViewModel.swift
#131 
🔒 Close #(issue-number1)
🔒 Close #(issue-number2)
- write here
- write here
- write here
- write here
- write here
=> MergeOrganizationforGoban

campair/campair/Utility/DateExtension.swift, campair/campair/View/Editor/Main/EditorMainView.swift
🔒 Close #130 
campair/campair/Utility/DateExtension.swift
- Change todayPhase depending on date
=> [Refactor] #130 Change todayPhase's context

campair/campair/UseCase/DictionaryDetailCategoryData.json
#139 
- Added DictionaryDetailCategoryData
- DictionaryDetailCategoryData.json
=> [Feature] Added DictionaryDetailCategoryData. #139

campair/campair/View/Dictionary/Detail/DictionaryDetailedView.swift
#141
🔒 Close #(issue-number1)
🔒 Close #(issue-number2)
- DictionaryDetailedView
- write here
- write here
- write here
- write here
=> 141 [Bug] DictionaryNavigationProblem

campair/campair.xcodeproj/project.pbxproj, campair/campair/View/Dictionary/Content/DictionaryContentView.swift, campair/campair/View/Dictionary/Detail/DictionaryDetailedView.swift, campair/campair/View/Dictionary/Main/DictionaryMainView.swift, campair/campair/View/Editor/Detail/EditorDetailView/EditorDetailView.swift, campair/campair/View/Editor/Detail/RecommendedEquipmentCardView.swift, campair/campair/View/Editor/Main/EditorMainView.swift
🔒 Close #142 
- write here
- write here
- write here
- write here
- write here
=> [Feat] #142 Navigation detail to content

campair/campair.xcodeproj/project.pbxproj, campair/campair/View/InterestEquipment/InterestEquipmentView.swift, campair/campair/View/TabbarView.swift
🔒 Close #150
modified:   campair/campair.xcodeproj/project.pbxproj
modified:   campair/campair/View/InterestEquipment/InterestEquipmentView.swift
modified:   campair/campair/View/TabbarView.swift
- Interest Tab 나누기
- InterestEquipmentView UI 만들기
- I added temp Image so there is loading gif in the equipmentPainting part.
=> [Feature] #150 make InterestEquipmentView UI 

campair/campair/View/Editor/Main/EditorEquipListView.swift, campair/campair/ViewModel/Dictionary/DictionaryDetailViewModel.swift
campair/campair/View/Editor/Main/EditorEquipListView.swift
campair/campair/ViewModel/Dictionary/DictionaryDetailViewModel.swift
remove comments
=> [fix] remove comments

campair/campair/View/InterestEquipment/InterestEquipmentView.swift
🔒 Close #175
campair/campair/View/InterestEquipment/InterestEquipmentView.swift
=> [refactor] change Squirrel Position

campair/campair.xcodeproj/project.pbxproj, campair/campair/Application/Assets.xcassets/launchScreenImage.imageset/Contents.json, campair/campair/Application/Assets.xcassets/launchScreenImage.imageset/launchScreenImage.svg, campair/campair/Application/CampairApp.swift, campair/campair/View/Launch Screen.storyboard
🔒 Close #179
campair/campair.xcodeproj/project.pbxproj
campair/campair/Application/Assets.xcassets/launchScreenImage.imageset/Contents.json
campair/campair/Application/Assets.xcassets/launchScreenImage.imageset/launchScreenImage.svg
campair/campair/Application/CampairApp.swift
campair/campair/View/Launch Screen.storyboard
=> [Feature] #179 add launchScreen 

campair/campair/View/InterestEquipment/InterestEquipmentView.swift
🔒 Close #184 
- "곧 떠나는 당신의 관심 장비" to "가볍게 떠나는 당신의 트렁크"
- "텅 비어있습니다" to "트렁크가 비어있어요!"
- re-writing
- UX writing
=> [Refact] #184 InterestEquipmentView re-writing
